"""empty message

Revision ID: acfd5712f3c2
Revises: d34d0b33f4b4
Create Date: 2023-08-28 22:19:04.554051

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'acfd5712f3c2'
down_revision = 'd34d0b33f4b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_collect_addtime'), 'collect', ['addtime'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collect_addtime'), table_name='collect')
    # ### end Alembic commands ###
